import React , { useLayoutEffect , useState, useEffect } from 'react'
import Head from 'next/head';
import Layout from '../../src/Layout/Layout';
import { Button } from '@mantine/core';
import MangeProducts from '../../src/components/customs/MangeProducts/MangeProducts';
import { useSelector , useDispatch } from 'react-redux';
import { getProduct } from './../../src/redux/slice/productSlice';
import { getCategory } from './../../src/redux/slice/categorySlice';
import { RootState } from '../../src/redux/store/store';
import ModalAddProduct from '../../src/components/customs/ModalAddProduct/ModalAddProduct';

function index() {
    const products = useSelector((store:RootState) => store.productSlice);
    const categorys = useSelector((store:RootState) => store.categorySlice);
    const [modalAdd , setModalAdd] = useState<boolean>(false);
 
    const [IsProduct , setIsProduct] = useState<boolean>(true)

    const dispatch = useDispatch()

    useEffect(()=>{
        dispatch(getProduct())
        dispatch(getCategory())
    },[])

    // console.log(products)

  return (
    <div dir='rtl' className='relarive font-IR'>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {/* <div className={`${(visible) ? "" : "hidden"}`}>
      <LoadingOverlay visible={visible} overlayBlur={8} 
    loaderProps={{ size: 'xl', color: '#5500FF', variant: 'oval' }}
    overlayOpacity={0.3}
    overlayColor="#b5b5b5" />
    </div> */}
    <Layout>
        <div className="my-12 font-IR">
            <div className="flex justify-around p-2">
                <h1 className="text-3xl font-bold">
                    پنل  مدیریت فروشگاه
                </h1>
                <div className='border rounded-lg border-[#5500FF]'>
                    <Button onClick={()=>{setIsProduct(true)}} className="font-IR" variant="subtle" size='md' radius="md">کالاها</Button>
                    <Button onClick={()=>{setIsProduct(false)}} className="font-IR" variant="subtle" size='md' radius="md">سفارش ها</Button>
                </div>
            </div>
            {(IsProduct) ? <MangeProducts products={products?.product} category={categorys?.category} openModal={setModalAdd} /> : ""}
            
        </div>
        <ModalAddProduct open={modalAdd} openModal={setModalAdd} category={categorys?.category}/>
        
    </Layout>
</div>
  )
}

export default index