import React,{ useEffect , useState } from 'react'
import Head from 'next/head';
import Layout from './../../src/Layout/Layout';
import AllProduct from './../../src/components/customs/AllProduct/AllProduct';
import { useSelector } from "react-redux";
import { LoadingOverlay } from '@mantine/core';
import { RootState } from '../../src/redux/store/store';

function products() {
  const product = useSelector((store:RootState) => store.productSlice);
  const category = useSelector((store:RootState) => store.categorySlice);
  const [visible, setVisible] = useState<boolean>(false);

  useEffect(()=>{
    if(product.status === "succeeded" && category.status === "succeeded"){
      setVisible(false)
    }
    else{
      setVisible(true)
    }
  },[product , category])

  
  return (
    <div dir='rtl' className='relarive'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${(visible) ? "" : "hidden"}`}>
        <LoadingOverlay visible={visible} overlayBlur={8} 
      loaderProps={{ size: 'xl', color: '#5500FF', variant: 'oval' }}
      overlayOpacity={0.3}
      overlayColor="#b5b5b5" />
        {/* ...other content */}
      </div>
      <Layout className={`${(visible) ? "hidden" : ""}`}>
        <AllProduct/>
      </Layout>
  </div>
  )
}

export default products