import React from 'react'
import Head from 'next/head';
import Layout from './../../src/Layout/Layout';
import AllProduct from './../../src/components/customs/AllProduct/AllProduct';

function products() {
  return (
    <div dir='rtl' className='relarive'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <AllProduct/>
      </Layout>
  </div>
  )
}

export default products