import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../src/Layout/Layout'
import styles from '../styles/Home.module.css'
import Main from './../src/components/customs/Main/Main';

const Home: NextPage = ({data}:any) => {

  console.log(data)

  return (
    <div dir='rtl' className='relarive'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Main/>
      </Layout>
    </div>
  )
}

export default Home


export async function  getStaticProps() {

  const res = await fetch('http://localhost:8000/store/product')
  const data = await res.json()

  return { 
    props: {
      data,
    } 
  }
}
